name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '**.c'
      - '**.h'
      - '**.tspec'
      - '.github/workflows/main.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build strum
        run: |
          git clone --depth 1 https://github.com/Strongleong/Strum strum
          cd strum
          cc build.c -o build
          ./build -c gcc
          echo "$PWD/out" >> "$GITHUB_PATH"

      - name: Build
        run: |
          cc build.c -o build
          ./build

      - name: Test
        run: ./build tests
